function k(b,a,c,d){b.s.Kb(b.nb,a,c,d,void 0)}function m(b,a,c,d){b.s.oa?k(b,a,c,d):b.s.Pe()._OnMessageFromDOM({type:"event",component:b.nb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.s.D(b.nb,a,c)}function t(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Wb||(b.s.Ie(b.Zd),b.Wb=!0)}window.pa=class{constructor(b,a){this.s=b;this.nb=a;this.Wb=!1;this.Zd=()=>this.Pa()}kd(){}Pa(){}};function aa(b){-1!==b.eb&&(self.clearTimeout(b.eb),b.eb=-1)}
window.De=class{constructor(b){this.Oc=b;this.cf=5;this.eb=-1;this.Zb=-Infinity;this.$d=()=>{this.eb=-1;this.Zb=Date.now();this.sb=!0;this.Oc();this.sb=!1};this.Cd=this.sb=!1}j(){aa(this);this.$d=this.Oc=null}};"use strict";function ba(b,a){n(b,"get-element",c=>{const d=b.ma.get(c.elementId);return a(d,c)})}
window.Af=class extends self.pa{constructor(b,a){super(b,a);this.ma=new Map;this.Nc=!0;t(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=this.ma.get(c);this.Nc&&d.parentElement.removeChild(d);this.ma.delete(c)}],["set-visible",c=>{this.Nc&&(this.ma.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.Nc){var d=this.ma.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=
c.height+"px";c=c.fontSize;null!==c&&(d.style.fontSize=c+"em")}}],["update-state",c=>{this.ma.get(c.elementId);throw Error("required override");}],["focus",c=>this.Ic(c)],["set-css-style",c=>{const d=this.ma.get(c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{this.ma.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.ma.get(c.elementId).removeAttribute(c.name)}]]);ba(this,c=>c)}Ic(b){var a=this.ma.get(b.elementId);
b.focus?a.focus():a.blur()}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent);let ea=0;function w(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.qf?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.uf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let fa=!1,ha=!1;
function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let y=new Audio;const ja={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;
async function ka(b){b=await na(b);return(new TextDecoder("utf-8")).decode(b)}function na(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const z=[];let C=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let oa=0;const qa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");qa.push(b)};const ra=new Set(["cordova","playable-ad","instant-games"]);
let sa=!1;
window.da=class b{constructor(a){this.oa=a.wf;this.za=null;this.ba="";this.bb=a.tf;this.Gb={};this.Va=this.wa=null;this.Tb=[];this.H=this.Aa=null;this.Xc=!1;this.Gd=0;this.ub=null;this.ab=-1;this.kf=()=>this.We();this.$a=[];this.A=a.be;this.Xb="file"===location.protocol.substr(0,4);!this.oa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.oa=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.oa=!1;if("cordova"===this.A&&this.oa)if(v){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.oa=!1)}else this.oa=!1;this.ac=this.ta=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.D("runtime","cordova-fetch-local-file",c=>this.Se(c));this.D("runtime","create-job-worker",()=>this.Te());"cordova"===this.A?document.addEventListener("deviceready",()=>this.vd(a)):this.vd(a)}j(){this.Ac();
this.za&&(this.za=this.za.onmessage=null);this.wa&&(this.wa.terminate(),this.wa=null);this.Va&&(this.Va.j(),this.Va=null);this.H&&(this.H.parentElement.removeChild(this.H),this.H=null)}ze(){return ca&&"cordova"===this.A}vc(){const a=navigator.userAgent;return ca&&ra.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}xe(){return v}pd(){return v&&ra.has(this.A)}async vd(a){"macos-wkwebview"===this.A&&this.Lc({type:"ready"});if("playable-ad"===this.A){this.ta=self.c3_base64files;
this.ac={};await this.Le();for(let d=0,e=a.fb.length;d<e;++d){var c=a.fb[d];this.ac.hasOwnProperty(c)?a.fb[d]={qf:!0,uf:this.ac[c]}:this.ta.hasOwnProperty(c)&&(a.fb[d]=URL.createObjectURL(this.ta[c]))}}a.sf?this.ba=a.sf:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.yf&&(this.Gb=a.yf);c=new MessageChannel;this.za=c.port1;this.za.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.Ve(d));this.ub=new self.Ae(this);await ta(this.ub);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.oa?await this.Re(a,c.port2):await this.Qe(a,c.port2)}Cc(a){a=this.Gb.hasOwnProperty(a)?this.Gb[a]:a.endsWith("/workermain.js")&&this.Gb.hasOwnProperty("workermain.js")?
this.Gb["workermain.js"]:"playable-ad"===this.A&&this.ta.hasOwnProperty(a)?this.ta[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async qc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Xb)return a=await this.Ib(d.pf?a:this.bb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}ra(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}ud(a){var c=this.ba,d=location.href,e=this.ra(),f=this.ia(),g=window.devicePixelRatio,h=b.jb(),l=a.Hf,p=window.cr_previewImageBlobs||this.ta,q=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.Df||"";a=a.be;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.ub;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,
isFullscreen:h,projectData:l,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.Ff,jobScheduler:{inputPort:B.Wc,outputPort:B.cd,maxNumWorkers:B.gf},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.bb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.bb+"opus.wasm.wasm",isFileProtocol:this.Xb,isiOSCordova:this.ze(),isiOSWebView:this.vc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Re(a,
c){const d=this.Cc(a.xf);"preview"===this.A?(this.wa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const p=q=>{this.wa.removeEventListener("message",p);q.data&&"ok"===q.data.type?h():l()};this.wa.addEventListener("message",p);this.wa.postMessage({type:"construct-worker-init","import":(new URL(d,this.ba)).toString()})})):this.wa=await this.qc(d,this.ba,{type:"module",name:"Runtime",pf:!0});this.H=document.createElement("canvas");this.H.style.display="none";
const e=this.H.transferControlToOffscreen();document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.jd||[],g=a.fb;f=await Promise.all(f.map(h=>this.Qa(h)));g=await Promise.all(g.map(h=>this.Qa(h)));if("cordova"===this.A)for(let h=0,l=a.oc.length;h<l;++h){const p=a.oc[h],q=p[0];if(q===a.gd||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.Qa(q)}this.wa.postMessage(Object.assign(this.ud(a),{type:"init-runtime",
isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.oc,mainProjectScript:a.gd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ua(this.ub)]);this.Tb=E.map(h=>new h(this));this.td();va(this.Aa);self.c3_callFunction=(h,l)=>{var p=this.Aa;return p.s.rd(p.nb,"js-invoke-function",{name:h,params:l},void 0,void 0)};"preview"===this.A&&(self.goToLastErrorScript=()=>this.Kb("runtime","go-to-last-error-script"))}async Qe(a,c){this.H=document.createElement("canvas");
this.H.style.display="none";document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Tb=E.map(g=>new g(this));this.td();var d=a.fb.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.jd)&&d.unshift(...a.jd);d=await Promise.all(d.map(g=>this.Qa(g)));await Promise.all(d.map(g=>w(g)));d=self.C3_ProjectScriptsStatus;const e=a.gd,f=a.oc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Qa(h),await w(h),"preview"!==
this.A||d[g]||this.xd(g,"main script did not run to completion")}catch(l){this.xd(g,l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Qa(h),await w(h);"preview"===this.A&&"object"!==typeof self.zf.Bf?(this.Ob(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.ud(a),
{isInWorker:!1,messagePort:c,canvas:this.H,runOnStartupFunctions:qa}),va(this.Aa),this.wd(),this.Va=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Va,a))}xd(a,c){this.Ob();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}wd(){this.Ob()}Ob(){const a=window.mf;a&&(a.parentElement.removeChild(a),window.mf=null)}async Te(){const a=
await wa(this.ub);return{outputPort:a,transferables:[a]}}Pe(){if(this.oa)throw Error("not available in worker mode");return this.Va}Kb(a,c,d,e,f){this.za.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}rd(a,c,d,e,f){const g=oa++,h=new Promise((l,p)=>{G.set(g,{resolve:l,reject:p})});this.za.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ue(a);
if("result"===c)this.Xe(a);else if("runtime-ready"===c)this.Ye();else if("alert-error"===c)this.Ob(),alert(a.message);else if("creating-runtime"===c)this.wd();else throw Error(`unknown message '${c}'`);}Ue(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Nb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Nb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,
h);this.Nb(f,!1,""+h)}):this.Nb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Nb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.za.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Xe(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}D(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
e.set(c,d)}static xa(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}td(){for(const a of this.Tb)if("runtime"===a.nb){this.Aa=a;return}throw Error("cannot find runtime DOM handler");}Ve(a){this.Kb("debugger","message",a)}Ye(){for(const a of this.Tb)a.kd()}static jb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||sa)}static Pb(a){sa=!!a}Ie(a){this.$a.push(a);this.Kc()}$e(a){a=this.$a.indexOf(a);if(-1===a)throw Error("invalid callback");
this.$a.splice(a,1);this.$a.length||this.Ac()}Kc(){-1===this.ab&&this.$a.length&&(this.ab=requestAnimationFrame(this.kf))}Ac(){-1!==this.ab&&(cancelAnimationFrame(this.ab),this.ab=-1)}We(){this.ab=-1;for(const a of this.$a)a();this.Kc()}Fa(a){this.Aa.Fa(a)}Oa(a){this.Aa.Oa(a)}Jc(){this.Aa.Jc()}Mb(a){this.Aa.Mb(a)}ye(){return!!ja["audio/webm; codecs=opus"]}async af(a){a=await this.rd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ge(a){this.Xc=!0;this.Gd=a}we(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||
"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}qd(a){return!this.we(a)}async Qa(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Xb&&this.qd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Ib(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Se(a){const c=a.filename;switch(a.as){case "text":return await this.se(c);case "buffer":return await this.Ib(c);default:throw Error("unsupported type");}}nd(a){const c=window.cordova.file.applicationDirectory+
"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async se(a){a=await this.nd(a);return await ka(a)}Bc(){if(z.length&&!(8<=C)){C++;var a=z.shift();this.Me(a.filename,a.vf,a.nf)}}Ib(a){return new Promise((c,d)=>{z.push({filename:a,vf:e=>{C--;this.Bc();c(e)},nf:e=>{C--;this.Bc();d(e)}});this.Bc()})}async Me(a,c,d){try{const e=await this.nd(a),f=await na(e);c(f)}catch(e){d(e)}}Lc(a){if("windows-webview2"===this.A)window.chrome.webview.postMessage(JSON.stringify(a));
else if("macos-wkwebview"===this.A)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async Le(){const a=[];for(const [c,d]of Object.entries(this.ta))a.push(this.Ke(c,d));await Promise.all(a)}async Ke(a,c){if("object"===typeof c)this.ta[a]=new Blob([c.str],{type:c.type}),this.ac[a]=c.str;else{let d=await this.Oe(c);d||(d=this.Ne(c));this.ta[a]=d}}async Oe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Ne(a){a=this.Ze(a);return this.Je(a.data,a.rf)}Ze(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{rf:a,data:d}}Je(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=a.charCodeAt(l++)|a.charCodeAt(l++)<<8|a.charCodeAt(l++)<<16|a.charCodeAt(l++)<<24;for(d&=
3;d--;)f[l]=a.charCodeAt(l),++l;return new Blob([f],{type:c})}};"use strict";const H=self.da;function xa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ya=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},za={dispatchUserScriptEvent:!0},J={dispatchRuntimeEvent:!0};
function Aa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ba(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await Ba(b)}finally{URL.revokeObjectURL(b)}}
function Ca(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Da(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Ca(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Ea(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Fa=new Set(["input","textarea","datalist","select"]),Ga=new Set(["canvas","body","html"]);function L(b){Ga.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ha(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Da(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ia=!1;document.addEventListener("pause",()=>Ia=!0);document.addEventListener("resume",()=>Ia=!1);function va(b){b.Fd=!0;b.$c=b.s.ra();b.vb=b.s.ia()}async function Ja(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ka(b){return await self.C3_GetSvgImageSize(b.blob)}
function La(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ma(b){self.setTimeout(()=>{b.Ed=!0},1E3);"cordova"===b.s.A?(document.addEventListener("pause",()=>Na(b,!0)),document.addEventListener("resume",()=>Na(b,!1))):document.addEventListener("visibilitychange",()=>Na(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ia)}}
function Oa(b){b.zd||(b.zd=!0,window.addEventListener("deviceorientation",a=>{b.Z||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Pa(b){b.yd||(b.yd=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Qa(b){await Aa(b.url)}
function Ra(b,a){b.Hd=a.message;-1===b.Rc&&(b.Rc=setTimeout(()=>{b.Rc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Hd)},250))}function M(b){if(!b.Z){var a=H.jb();a&&"any"!==b.ed&&Sa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ra(),innerHeight:b.ia()})}}function Ta(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:H.jb(),innerWidth:b.ra(),innerHeight:b.ia()})}
function Na(b,a){a?b.s.Ac():b.s.Kc();k(b,"visibilitychange",{hidden:a})}function Ua(b,a,c){"Backspace"===c.key&&L(c);if(!b.Z){var d=ya.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function Va(b,a,c,d){b.Z||xa(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Wa(b){window!==window.top&&window.focus();Xa(b.target)&&document.activeElement&&!Xa(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.Z){if(b.Db&&"pointermove"!==a){var d=b.Db;d.sb||(aa(d),d.Zb=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.Ab);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:(c.movementX||0)+b.ic,movementY:(c.movementY||0)+b.jc,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||
0,twist:c.twist||0,timeStamp:c.timeStamp},I);b.ic=0;b.jc=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Va(b,d,c,za),b.Ab=c.buttons)}}
function Ya(b,a,c){if(!b.Z&&!xa(c)){var d=b.Ab;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.Ab=c.buttons;Va(b,c.type,c,za)}}
function O(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.ca,pageX:f.pageX,pageY:f.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function Za(b,a,c){document.body.style.transform="";b.ca=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.ca=a))}}function $a(b,a,c,d){const e=b.ra(),f=b.ia();b.cb=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.jb()}):10>d&&ab(b,e,f,d+1)}
function ab(b,a,c,d){-1!==b.cb&&clearTimeout(b.cb);b.cb=setTimeout(()=>$a(b,a,c,d),48)}
function Sa(b){b=b.ed;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Xa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.xa(class extends self.pa{constructor(b){super(b,"runtime");this.Md=!0;this.Fd=!1;this.cb=-1;this.ed="any";this.yd=this.zd=!1;this.Ia=null;this.Z=!1;this.Hd="";this.Rc=-1;this.Ua=this.Db=null;this.jc=this.ic=0;this.Ed=!1;this.$c=b.ra();this.vb=b.ia();this.ca=this.Fb=0;b.D("canvas","update-size",d=>{var e=this.s;e.Xc||(e=e.H,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",
d.displayScale),this.Md&&(e.style.display="",this.Md=!1))});b.D("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.D("runtime","raster-svg-image",d=>Ja(d));b.D("runtime","get-svg-image-size",d=>Ka(d));b.D("runtime","set-target-orientation",d=>{this.ed=d.targetOrientation});b.D("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.D("runtime",
"post-to-debugger",d=>La(d));b.D("runtime","go-to-script",d=>La(d));b.D("runtime","before-start-ticking",()=>Ma(this));b.D("runtime","debug-highlight",d=>{if(d.show){this.Ia||(this.Ia=document.createElement("div"),this.Ia.id="inspectOutline",document.body.appendChild(this.Ia));var e=this.Ia;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ia&&(this.Ia.style.display="none")});b.D("runtime",
"enable-device-orientation",()=>Oa(this));b.D("runtime","enable-device-motion",()=>Pa(this));b.D("runtime","add-stylesheet",d=>Qa(d));b.D("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.D("runtime","alert",d=>this.Fc(d));b.D("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.D("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=document.createElement("h1");
e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.s.H.style.display="";this.s.Ge(d.duration)});b.D("runtime","export-to-video-progress",d=>Ra(this,d));b.D("runtime","exported-to-video",d=>{window.lf({type:"exported-video",blob:d.blob,time:d.time})});b.D("runtime","exported-to-image-sequence",d=>{window.lf({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ea(e)||d.preventDefault()});const c=b.H;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);c.addEventListener("selectstart",L);c.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),c.addEventListener("pointerdown",L)):c.addEventListener("touchstart",L);this.Ab=
0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ha,{passive:!1});window.addEventListener("wheel",Ha,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.Z&&this.Fd){var d=this.ra();var e=this.ia();if(this.s.pd()){if(this.Ed){if(this.$c===d&&e<this.vb){this.Fb=this.vb-e;Za(this,this.vb,this.Fb);d=void 0;break a}0<this.Fb&&(this.Fb=0,Za(this,e,this.Fb))}this.$c=d;this.vb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,
devicePixelRatio:window.devicePixelRatio,isFullscreen:H.jb()});this.s.vc()&&(-1!==this.cb&&clearTimeout(this.cb),$a(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",()=>M(this));window.addEventListener("mozfullscreenchange",()=>M(this));window.addEventListener("fullscreenerror",d=>Ta(this,d));window.addEventListener("webkitfullscreenerror",d=>Ta(this,d));window.addEventListener("mozfullscreenerror",d=>Ta(this,
d));if(b.vc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ea(f)}else d=!1}d||(document.scrollingElement.scrollTop=
0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.Pb(!0),M(this)):"exited-fullscreen"===d?(H.Pb(!1),M(this)):console.warn("Unknown wrapper message: ",d)};this.Wa=new Set;this.cc=new WeakSet;this.ya=!1}kd(){window.addEventListener("focus",()=>{k(this,"window-focus",null,J)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},J);this.Ab=0});window.addEventListener("focusin",a=>{a=a.target;(Fa.has(a.tagName.toLowerCase())||
Ea(a))&&k(this,"keyboard-blur",null,J)});window.addEventListener("keydown",a=>Ua(this,"keydown",a));window.addEventListener("keyup",a=>Ua(this,"keyup",a));window.addEventListener("dblclick",a=>Va(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.Z||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.ca,pageX:a.pageX,pageY:a.pageY+this.ca,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{Wa(a);N(this,"pointerdown",a)}),this.s.oa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Db=new self.De(()=>{N(this,"pointermove",this.Ua);this.Ua=null}),this.Db.Cd=!0,window.addEventListener("pointerrawupdate",a=>{this.Ua&&(this.ic+=this.Ua.movementX||0,this.jc+=this.Ua.movementY||0);this.Ua=a;a=this.Db;if(-1===a.eb){var c=Date.now(),d=c-a.Zb,e=a.cf;d>=e&&a.Cd?(a.Zb=c,a.sb=!0,a.Oc(),a.sb=!1):a.eb=self.setTimeout(a.$d,Math.max(e-d,4))}})):window.addEventListener("pointermove",
a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Wa(a);Ya(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>Ya(this,"pointermove",a)),window.addEventListener("mouseup",a=>Ya(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Wa(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",
a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=()=>this.Jc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.s.xe()&&!this.s.pd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Za(this,this.ia(),
navigator.virtualKeyboard.boundingRect.height)}))}ra(){return this.s.ra()}ia(){return this.s.ia()}Jc(){var b=[...this.Wa];this.Wa.clear();if(!this.ya)for(const a of b)(b=a.play())&&b.catch(()=>{this.cc.has(a)||this.Wa.add(a)})}Fa(b){if("function"!==typeof b.play)throw Error("missing play function");this.cc.delete(b);let a;try{a=b.play()}catch(c){this.Wa.add(b);return}a&&a.catch(()=>{this.cc.has(b)||this.Wa.add(b)})}Oa(b){this.Wa.delete(b);this.cc.add(b)}Mb(b){this.ya=!!b}Fc(b){alert(b.message)}});
"use strict";async function ta(b){if(b.bf)throw Error("already initialised");b.bf=!0;var a=b.Ba.Cc(("playable-ad"===b.Ba.A?b.Ba.bb:"")+"dispatchworker.js");b.Qc=await b.Ba.qc(a,b.mb,{name:"DispatchWorker"});a=new MessageChannel;b.Wc=a.port1;b.Qc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.cd=await wa(b)}function ua(b){return[b.Wc,b.cd]}
async function wa(b){const a=b.Nd.length;var c=b.Ba.Cc(("playable-ad"===b.Ba.A?b.Ba.bb:"")+"jobworker.js");c=await b.Ba.qc(c,b.mb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Qc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Nd.push(c);return e.port1}
self.Ae=class{constructor(b){this.Ba=b;this.mb=b.ba;this.mb="preview"===b.A?this.mb+"workers/":this.mb+b.bb;this.gf=Math.min(navigator.hardwareConcurrency||2,16);this.Qc=null;this.Nd=[];this.cd=this.Wc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.da({wf:!1,xf:"workermain.js",fb:["scripts/c3runtime.js"],oc:[],gd:"",tf:"scripts/",jd:[],be:"html5"}));"use strict";function bb(){}
function cb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function db(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.da.xa(class extends self.pa{constructor(b){super(b,"browser");this.A="";t(this,[["get-initial-state",a=>this.Hc(a)],["ready-for-sw-messages",()=>cb(this)],["alert",a=>this.Fc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ic(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>db(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.Cf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.A||"macos-wkwebview"===this.A)self.da.Pb(!0),
this.s.Lc({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof
Promise&&d.catch(bb)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.A||"macos-wkwebview"===this.A)self.da.Pb(!1),this.s.Lc({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(bb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",
a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:
{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}Hc(b){this.A=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,
referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}Fc(b){alert(b.message)}Ic(b){b=b.isFocus;if("nwjs"===this.A){const a="nwjs"===this.A?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
self.da.xa(class extends self.pa{constructor(b){super(b,"mouse");t(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.s.H.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function eb(b,a){a=a.type;let c=!0;0===a?c=await fb():1===a&&(c=await hb());k(b,"permission-result",{type:a,result:c})}async function fb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function hb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.da.xa(class extends self.pa{constructor(b){super(b,"touch");n(this,"request-permission",a=>eb(this,a))}});"use strict";const ib=180/Math.PI;
async function jb(b,a){if(a.isiOSCordova||a.isSafari)b.fc=!0;b.fd=a.timeScaleMode;b.Sd=["equalpower","HRTF","soundfield"][a.panningModel];b.Dd=["linear","inverse","exponential"][a.distanceModel];b.Td=a.refDistance;b.Rd=a.maxDistance;b.Vd=a.rolloffFactor;if(b.s.Xc)b.fc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.Gd)});else{var c={latencyHint:a.latencyHint};b.Yd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");kb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&kb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Sa=b.g.createGain();b.Sa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function lb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,l=a.vol,p=a.pos,q=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Od=g;mb(b,g);try{b.$=await nb(b,c,d,e,g,f);if(q){Q(b.$,!0);var r=b.$,B=q.innerAngle,la=q.outerAngle,ma=q.outerGain;if(r.tb){ob(r,q.x,q.y,q.angle);var D=self.gb.He;r.ua[0]!==D(B)&&(r.ua[0]=D(B),
r.F.coneInnerAngle=D(B));r.ua[1]!==D(la)&&(r.ua[1]=D(la),r.F.coneOuterAngle=D(la));r.ua[2]!==ma&&(r.ua[2]=ma,r.F.coneOuterGain=ma)}q.hasOwnProperty("uid")&&(b.$.sa=q.uid)}else"number"===typeof A&&0!==A?(R(b.$,!0),pb(b.$,A)):(Q(b.$,!1),R(b.$,!1));b.$.Play(h,l,p,x)}catch(Db){console.error("[Construct] Audio: error starting playback: ",Db);return}finally{c=b.Cb.get(g);if(!c)throw Error("expected pending tag");c.hd--;0===c.hd&&(c.resolve(),b.Cb.delete(g))}u(b)}
async function qb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await rb(b,c);for(const q of S(b,c)){c=q;var f=d,g=e,h=a;if(!c.Ta){var l=c.G.gain;l.cancelScheduledValues(0);var p=c.u.g.currentTime;g=p+g;l.setValueAtTime(l.value,p);l.linearRampToValueAtTime(f,g);c.Ma=f;c.qb=g;c.Xd=h}}T(b)}async function sb(b,a){const c=a.tag;a=a.rate;await rb(b,c);for(const d of S(b,c))b=d,b.na!==a&&(b.na=a,b.Ga())}
async function tb(b,a){const c=a.tag;a=a.pos;await rb(b,c);for(const d of S(b,c))d.xc(a)}async function ub(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await nb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function vb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function wb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.he(b,...e);else if("delay"===c)e=new self.fe(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.ee(b,c.ja,...e);var f=a.bufferType;c.Ad=a.bufferOriginalUrl;c.Bd=f}else if("flanger"===c)e=new self.ie(b,...e);else if("phaser"===c)e=new self.ke(b,...e);else if("gain"===c)e=
new self.je(b,...e);else if("stereopan"===c)e=new self.me(b,...e);else if("tremolo"===c)e=new self.ne(b,...e);else if("ringmod"===c)e=new self.le(b,...e);else if("distortion"===c)e=new self.ge(b,...e);else if("compressor"===c)e=new self.de(b,...e);else if("analyser"===c)e=new self.ce(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.la.get(d);e||(e=[],b.la.set(d,e));a.Ld=e.length;a.ga=d;e.push(a);xb(b,d);yb(b)}
async function zb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(const e of b.J)e.Da()&&1===c||!e.Da()&&2===c?d.push(e):e.j();b.J=d}for(const e of b.la.values())for(const f of e)f.j();b.la.clear();b.mc=a.timeScale;b.Tc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);b.ya=a.isSilent;b.s.Mb(b.ya);b.bc=a.masterVolume;b.Sa.gain.value=b.bc;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>wb(b,f))));await Promise.all(d);
await Promise.all(a.playing.map(e=>Ab(b,e,c)));T(b)}async function Bb(b,a){try{const c=b.g.suspend(a.time);b.Kd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.Kb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Cb(d)),b.Kd=!0);await c}catch(c){Cb(c)}}
function kb(b){b.Vb||(b.Vc=!1,window.addEventListener("pointerup",b.Ca,!0),window.addEventListener("touchend",b.Ca,!0),window.addEventListener("click",b.Ca,!0),window.addEventListener("keydown",b.Ca,!0),b.Vb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ka)if(g.ib()===c)return await Eb(g),g;if(f)return null;if(e&&(b.fc||b.Jd)){f=0;for(let h=0,l=b.ka.length;h<l;++h)g=b.ka[h],b.ka[f]=g,g.Da()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.Yd;e&&f&&(b.Jd=!0);c=!e||b.fc||f?new self.qe(b,a,c,d,e,f):new self.oe(b,a,c,d,e);b.ka.push(c);await Eb(c);b.Qd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Qd.add(a));return c}
function Fb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.qa()}function xb(b,a){let c=b.qa();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.S(b.qa()):e.S(d[f+1].N())}}for(const f of S(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ja&&b.ad===a&&(b.Ja.disconnect(),b.Ja.connect(c))}
function*S(b,a){if(a)for(const c of b.J)b=c.ga,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.$&&!b.$.U()&&(yield b.$)}function Gb(b,a,c){return c?b.s.af(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Hb(b,a){let c=0;for(let d=0,e=b.J.length;d<e;++d){const f=b.J[d];b.J[c]=f;f.O===a?f.j():++c}b.J.length=c}
async function nb(b,a,c,d,e,f){for(const g of b.J)if(g.ib()===c&&(g.pc()||f))return g.ga=e,g;a=await P(b,a,c,d,f);e="html5"===a.Mc?new self.pe(a.u,a,e):new self.re(a.u,a,e);b.J.push(e);return e}function mb(b,a){let c=b.Cb.get(a);if(!c){let d=null;c={hd:0,promise:new Promise(e=>d=e),resolve:d};b.Cb.set(a,c)}c.hd++}function rb(b,a){a||(a=b.Od);return(b=b.Cb.get(a))?b.promise:Promise.resolve()}function T(b){if(0<b.Ra.size)u(b);else for(const a of b.J)if(!a.I&&!a.U()){u(b);break}}
function Ib(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function yb(b){b.Yc||(b.Yc=!0,Promise.resolve().then(()=>Jb(b)))}function Jb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.hb());k(b,"fxstate",{fxstate:a});b.Yc=!1}
async function Ab(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,l=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await nb(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ya[0]=f[0],b.Ya[1]=f[1],b.Ya[2]=f[2],f=d.orient,b.Xa[0]=f[0],b.Xa[1]=f[1],b.Xa[2]=f[2],e.setPosition(...b.Ya),e.setOrientation(...b.Xa),b.ua[0]=d.cia,b.ua[1]=d.coa,b.ua[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.sa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),pb(b,d));c.Play(l,p,q,0);a.isPlaying||c.kb();c.Ec(a)}}}function Cb(b){console.error("[Audio] Offline rendering error: ",b)}
self.gb=class extends self.pa{constructor(b){super(b,"audio");this.Sa=this.g=null;this.Vb=this.Vc=!1;this.Ca=()=>{if(!this.Vc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Vb&&(this.Vc=!0,window.removeEventListener("pointerup",this.Ca,!0),window.removeEventListener("touchend",this.Ca,!0),window.removeEventListener("click",this.Ca,!0),window.removeEventListener("keydown",
this.Ca,!0),this.Vb=!1)}};this.ka=[];this.J=[];this.$=null;this.Od="";this.Qd=new Set;this.Pd=-1;this.Cb=new Map;this.bc=1;this.ya=!1;this.fd=0;this.mc=1;this.Tc=0;this.Sd="HRTF";this.Dd="inverse";this.Td=600;this.Rd=1E4;this.Vd=1;this.aa=[0,0,0];this.Jd=this.fc=!1;this.Yd=this.s.ye();this.la=new Map;this.Ra=new Set;this.Kd=this.Yc=!1;this.ad="";this.Ja=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ja&&this.Ja.disconnect();this.ad=c.toLowerCase();this.Ja=this.g.createMediaStreamSource(a);this.Ja.connect(Fb(this,
this.ad))};this.Sb=null;self.C3Audio_GetOutputStream=()=>{this.Sb||(this.Sb=this.g.createMediaStreamDestination(),this.Sa.connect(this.Sb));return this.Sb.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>jb(this,a)],["play",a=>lb(this,a)],["stop",a=>{a=a.tag;for(const c of S(this,a))c.Ea()}],["stop-all",()=>{for(const a of this.J)a.Ea()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of S(this,c))a?d.kb():d.Lb();T(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;for(const d of S(this,
c))U(d,a)}],["fade-volume",a=>qb(this,a)],["set-master-volume",a=>{this.bc=a.vol;this.Sa.gain.value=this.bc}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of S(this,c))Kb(d,a)}],["set-silent",a=>{this.ya=a.isSilent;this.s.Mb(this.ya);for(const c of this.J)c.Qb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of S(this,c))d.yc(a)}],["set-playback-rate",a=>sb(this,a)],["set-stereo-pan",a=>{const c=a.tag;a=a.p;for(const d of S(this,c))R(d,!0),pb(d,a)}],["seek",a=>tb(this,a)],
["preload",a=>ub(this,a)],["unload",a=>vb(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.J)c.zc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>wb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.la.get(a.tag);!a||0>c||c>=a.length||(a[c].Y(d,e,f,g),yb(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=this.la.get(a);
if(c&&c.length){for(const d of c)d.j();this.la.delete(a);xb(this,a)}}],["tick",a=>{this.mc=a.timeScale;this.Tc=a.gameTime;this.Pd=a.tickCount;if(0!==this.fd)for(var c of this.J)c.Ga();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));for(const d of a.instPans){a=d.uid;for(const e of this.J)e.sa===a&&ob(e,d.x,d.y,d.angle)}}],["load-state",a=>zb(this,a)],["offline-render-audio",a=>
Bb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}qa(){return this.Sa}Jb(){return this.ya}Fa(b){this.s.Fa(b)}Oa(b){this.s.Oa(b)}Pa(){for(var b of this.Ra)b.Pa();b=this.g.currentTime;for(var a of this.J)a.Pa(b);a=this.J.filter(c=>!c.I&&!c.U()).map(c=>c.hb());k(this,"state",{tickCount:this.Pd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ra].map(c=>({tag:c.ga,index:c.Ld,peak:c.Za,rms:c.Ud,binCount:c.l.frequencyBinCount,freqBins:c.Id}))});0===
a.length&&0===this.Ra.size&&this.Wb&&(this.s.$e(this.Zd),this.Wb=!1)}static He(b){return b*ib}static od(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Be(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.da.xa(self.gb);"use strict";function Eb(b){b.$b||(b.$b=b.Dc());return b.$b}self.ld=class{constructor(b,a,c,d,e){this.u=b;this.jf=a;this.La=c;this.R=d;this.ef=e;this.Mc="";this.$b=null}j(){this.$b=this.u=null}Dc(){}V(){return this.u.V()}sc(){return this.jf}ib(){return this.La}rc(){return this.R}Da(){return this.ef}ha(){}};
"use strict";
self.oe=class extends self.ld{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Mc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.wb=this.xb=null;this.M.addEventListener("canplaythrough",()=>!0);this.Bb=this.V().createGain();this.zb=null;this.M.addEventListener("canplay",()=>{this.xb&&(this.xb(),this.wb=this.xb=null);!this.zb&&this.M&&(this.zb=this.V().createMediaElementSource(this.M),this.zb.connect(this.Bb))});this.onended=null;this.M.addEventListener("ended",()=>
{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.La}' error: `,f);this.wb&&(this.wb(f),this.wb=this.xb=null)})}j(){Hb(this.u,this);this.Bb.disconnect();this.Bb=null;this.zb.disconnect();this.zb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}Dc(){return new Promise((b,a)=>{this.xb=b;this.wb=a;this.M.src=this.La})}T(){return this.M}ha(){return this.M.duration}};"use strict";
async function Lb(b){if(b.Ha)return b.Ha;var a=b.u.s;if("cordova"===a.A&&a.qd(b.La)&&a.Xb)b.Ha=await a.Ib(b.La);else{a=await fetch(b.La);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ha=await a.arrayBuffer()}}async function Mb(b){if(b.ja)return b.ja;b.ja=await Gb(b.u,b.Ha,b.hf);b.Ha=null}
self.qe=class extends self.ld{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Mc="webaudio";this.ja=this.Ha=null;this.hf=!!f}j(){Hb(this.u,this);this.ja=this.Ha=null;super.j()}async Dc(){try{await Lb(this),await Mb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.La}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Nb=0;
function Q(b,a){a=!!a;b.tb!==a&&(b.tb=a,b.tb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Sd,b.F.distanceModel=b.u.Dd,b.F.refDistance=b.u.Td,b.F.maxDistance=b.u.Rd,b.F.rolloffFactor=b.u.Vd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.qa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.qa())))}
function R(b,a){a=!!a;b.Yb!==a&&(b.Yb=a,b.Yb?(Q(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.qa())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.qa())))}function pb(b,a){b.Yb&&b.dd!==a&&(b.fa.pan.value=a,b.dd=a)}function U(b,a){b.Ma=a;b.G.gain.cancelScheduledValues(0);b.qb=-1;b.G.gain.value=b.tc()}function Kb(b,a){a=!!a;b.Ta!==a&&(b.Ta=a,b.Qb())}
function ob(b,a,c,d){if(b.tb){var e=b.Ya,f=b.Xa,g=Math.cos(d);d=Math.sin(d);if(e[0]!==a||e[1]!==c||0!==e[2])e[0]=a,e[1]=c,e[2]=0,b.F.setPosition(...e);if(f[0]!==g||f[1]!==d||0!==f[2])f[0]=g,f[1]=d,f[2]=0,b.F.setOrientation(...f)}}function V(b){return b.Zc?b.u.Tc:performance.now()/1E3}
self.md=class{constructor(b,a,c){this.u=b;this.O=a;this.ga=c;this.Rb=Nb++;this.G=this.V().createGain();this.G.connect(this.qa());this.F=null;this.tb=!1;this.Ya=[0,0,0];this.Xa=[0,0,0];this.ua=[0,0,0];this.fa=null;this.Yb=!1;this.dd=0;this.I=!0;this.X=this.va=this.K=!1;this.Ma=1;this.Ta=!1;this.na=1;b=this.u.fd;this.Zc=1===b&&!this.Da()||2===b;this.qb=this.sa=-1;this.Xd=!1}j(){this.O=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}qa(){return Fb(this.u,this.ga)}sc(){return this.O.sc()}ib(){return this.O.ib()}rc(){return this.O.rc()}Da(){return this.O.Da()}U(){}pc(){}IsPlaying(){return!this.I&&!this.K&&!this.U()}Na(){}ha(){return this.O.ha()}Play(){}Ea(){}kb(){}Lb(){}Pa(b){-1!==this.qb&&b>=this.qb&&(this.qb=-1,this.Xd&&this.Ea(),Ib(this.u,"fade-ended",this.ga,this.Rb))}tc(){const b=this.Ma;return isFinite(b)?b:0}Jb(){return this.u.Jb()}Qb(){}yc(){}Ga(){}xc(){}zc(){}uc(){}hb(){var b=this.Rb,
a=this.ga,c=this.ha(),d=this.Ma,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ya,orient:this.Xa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.sa}}else f=null;return{aiid:b,tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Na(),playbackRate:this.na,uid:this.sa,bufferOriginalUrl:this.sc(),bufferUrl:"",bufferType:this.rc(),isMusic:this.Da(),isLooping:this.X,isMuted:this.Ta,resumePosition:this.uc(),pan:f,stereoPan:this.fa?this.dd:null}}Ec(b){var a=b.playbackRate;
this.na!==a&&(this.na=a,this.Ga());Kb(this,b.isMuted)}};"use strict";
self.pe=class extends self.md{constructor(b,a,c){super(b,a,c);this.O.Bb.connect(this.G);this.O.onended=()=>this.Gc()}j(){this.Ea();this.O.Bb.disconnect();super.j()}T(){return this.O.T()}Gc(){this.I=!0;this.sa=-1;Ib(this.u,"ended",this.ga,this.Rb)}U(){return this.T().ended}pc(){return this.I?!0:this.U()}Na(){let b=this.T().currentTime;this.X||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.T();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.O.ib()}' to position '${c}': `,e)}this.u.Fa(d);this.K=this.I=!1;this.X=b;this.na=1}Ea(){const b=this.T();b.paused||b.pause();this.u.Oa(b);this.I=!0;this.K=!1;this.sa=-1}kb(){if(!(this.K||this.I||this.U())){var b=this.T();b.paused||b.pause();this.u.Oa(b);this.K=!0}}Lb(){!this.K||this.I||this.U()||(this.u.Fa(this.T()),this.K=!1)}Qb(){this.T().muted=this.Ta||this.Jb()}yc(b){b=!!b;this.X!==b&&(this.X=
b,this.T().loop=b)}Ga(){let b=this.na;this.Zc&&(b*=this.u.mc);try{this.T().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}xc(b){if(!this.I&&!this.U())try{this.T().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}uc(){return this.Na()}zc(b){b?this.IsPlaying()?(this.T().pause(),this.va=!0):this.va=!1:this.va&&(this.u.Fa(this.T()),this.va=!1)}};"use strict";function W(b){b.o&&b.o.disconnect();b.o=null;b.lb=null}
self.re=class extends self.md{constructor(b,a,c){super(b,a,c);this.o=null;this.dc=d=>this.Gc(d);this.Uc=!0;this.lb=null;this.P=this.ec=this.hc=0;this.bd=1}j(){this.Ea();W(this);this.dc=null;super.j()}Gc(b){this.K||this.va||b.target!==this.lb||(this.I=this.Uc=!0,this.sa=-1,W(this),Ib(this.u,"ended",this.ga,this.Rb))}U(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Uc}pc(){return!this.o||this.I?!0:this.U()}Na(){let b;b=this.K?this.P:this.ec+(V(this)-this.hc)*this.na;this.X||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.bd=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.O.ja;this.o.connect(this.G);this.lb=this.o;this.o.onended=this.dc;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Uc=!1;this.X=b;this.na=1;this.hc=V(this);this.ec=c}Ea(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.sa=-1}kb(){this.K||this.I||this.U()||(this.P=this.Na(),this.X&&(this.P%=this.ha()),this.K=!0,this.o.stop(0))}Lb(){!this.K||this.I||this.U()||(W(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.O.ja,this.o.connect(this.G),this.lb=this.o,this.o.onended=this.dc,this.o.loop=this.X,U(this,this.Ma),this.Ga(),this.o.start(0,this.P),this.hc=V(this),this.ec=this.P,this.K=!1)}tc(){return super.tc()*this.bd}Qb(){this.bd=this.Ta||this.Jb()?0:1;U(this,this.Ma)}yc(b){b=!!b;this.X!==b&&(this.X=b,this.o&&(this.o.loop=b))}Ga(){let b=this.na;this.Zc&&(b*=this.u.mc);this.o&&(this.o.playbackRate.value=b)}xc(b){this.I||this.U()||(this.K?this.P=b:(this.kb(),this.P=
b,this.Lb()))}uc(){return this.P}zc(b){b?this.IsPlaying()?(this.va=!0,this.P=this.Na(),this.X&&(this.P%=this.ha()),this.o.stop(0)):this.va=!1:this.va&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.O.ja,this.o.connect(this.G),this.lb=this.o,this.o.onended=this.dc,this.o.loop=this.X,U(this,this.Ma),this.Ga(),this.o.start(0,this.P),this.hc=V(this),this.ec=this.P,this.va=!1)}Ec(b){super.Ec(b);this.P=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Ld=-1;this.R=this.ga="";this.m=null}j(){this.g=null}N(){}S(){}hb(){return{type:this.R,tag:this.ga,params:this.m}}}
self.he=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="filter";this.m=[a,c,d,e,f,g];this.v=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.C=this.g.createBiquadFilter();this.C.type=a;this.C.frequency.value=c;this.C.detune.value=d;this.C.Q.value=e;this.C.gain.vlaue=f;this.v.connect(this.C);this.v.connect(this.h);this.C.connect(this.i)}j(){this.v.disconnect();this.C.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.C.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.C.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.C.gain,a,c,d)}}};
self.fe=class extends Z{constructor(b,a,c,d){super(b);this.R="delay";this.m=[a,c,d];this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.yb=X(this);this.W=this.g.createDelay(a);this.W.delayTime.value=a;this.pb=X(this);this.pb.gain.value=c;this.v.connect(this.yb);this.v.connect(this.h);this.yb.connect(this.i);this.yb.connect(this.W);this.W.connect(this.pb);this.pb.connect(this.yb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.yb.disconnect();
this.W.disconnect();this.pb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){const e=self.gb.od;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.pb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.W.delayTime,a,c,d)}}};
self.ee=class extends Z{constructor(b,a,c,d){super(b);this.R="convolution";this.m=[c,d];this.Bd=this.Ad="";this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.ob=this.g.createConvolver();this.ob.normalize=c;this.ob.buffer=a;this.v.connect(this.ob);this.v.connect(this.h);this.ob.connect(this.i)}j(){this.v.disconnect();this.ob.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}hb(){const b=super.hb();b.bufferOriginalUrl=this.Ad;b.bufferUrl="";b.bufferType=this.Bd;return b}};
self.ie=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="flanger";this.m=[a,c,d,e,f];this.v=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.rb=X(this);this.rb.gain.value=e;this.W=this.g.createDelay(a+c);this.W.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.v.connect(this.W);this.v.connect(this.h);this.W.connect(this.i);this.W.connect(this.rb);this.rb.connect(this.W);this.B.connect(this.L);
this.L.connect(this.W.delayTime);this.B.start(0)}j(){this.B.stop(0);this.v.disconnect();this.W.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.rb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.rb.gain,a/100,c,d)}}};
self.ke=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="phaser";this.m=[a,c,d,e,f,g];this.v=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.C=this.g.createBiquadFilter();this.C.type="allpass";this.C.frequency.value=a;this.C.detune.value=c;this.C.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.v.connect(this.C);this.v.connect(this.h);this.C.connect(this.i);this.B.connect(this.L);this.L.connect(this.C.frequency);
this.B.start(0)}j(){this.B.stop(0);this.v.disconnect();this.C.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.C.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.C.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.je=class extends Z{constructor(b,a){super(b);this.R="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){const e=self.gb.od;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.me=class extends Z{constructor(b,a){super(b);this.R="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.ne=class extends Z{constructor(b,a,c){super(b);this.R="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.le=class extends Z{constructor(b,a,c){super(b);this.R="ringmod";this.m=[a,c];this.v=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Eb=X(this);this.Eb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Eb.gain);this.B.start(0);this.v.connect(this.Eb);this.v.connect(this.h);this.Eb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Eb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.ge=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="distortion";this.m=[a,c,d,e,f];this.v=X(this);this.lc=X(this);this.kc=X(this);b=d;.01>b&&(b=.01);this.lc.gain.value=b;this.kc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.nc=this.g.createWaveShaper();this.Pc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Pc[32768+e]=f,this.Pc[32768-
e-1]=-f;this.nc.curve=this.Pc;this.v.connect(this.lc);this.v.connect(this.h);this.lc.connect(this.nc);this.nc.connect(this.kc);this.kc.connect(this.i)}j(){this.v.disconnect();this.lc.disconnect();this.nc.disconnect();this.kc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.de=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
self.ce=class extends Z{constructor(b,a,c){super(b);this.R="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Id=new Float32Array(this.l.frequencyBinCount);this.Wd=new Uint8Array(a);this.Ud=this.Za=0;b=this.u;b.Ra.add(this);T(b)}j(){this.u.Ra.delete(this);this.l.disconnect();super.j()}Pa(){this.l.getFloatFrequencyData(this.Id);this.l.getByteTimeDomainData(this.Wd);const b=this.l.fftSize;let a=this.Za=0;for(var c=0;c<b;++c){let d=(this.Wd[c]-
128)/128;0>d&&(d=-d);this.Za<d&&(this.Za=d);a+=d*d}c=self.gb.Be;this.Za=c(this.Za);this.Ud=c(Math.sqrt(a/b))}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};"use strict";function Ob(){const b=self.RealFile||self.File;return"function"===typeof navigator.canShare&&navigator.canShare({files:[new b(["test file"],"test.txt",{})]})}function Pb(){return window.plugins&&window.plugins.socialsharing}
async function Qb(b,a){var c=a.text;const d=a.title,e=a.url;a=a.files.slice(0);const f=0<a.length,g=Pb();if(g){const l={};c&&(l.message=c);d&&(l.subject=d);e&&(l.url=e);if(f){c=0;for(var h of a)c+=h.size;try{const p=await Rb(Math.floor(1.25*c));l.files=await Promise.all(a.map(q=>Sb(q,p)))}catch(p){console.log("[Share plugin] Share failed: ",p);k(b,"share-failed");return}}g.shareWithOptions(l,()=>{k(b,"share-completed")},p=>{console.log("[Share plugin] Share failed: ",p);k(b,"share-failed")})}else{h=
{};c&&(h.text=c);d&&(h.title=d);e&&(h.url=e);f&&(h.files=a);try{await navigator.share(h),k(b,"share-completed")}catch(l){console.log("[Share plugin] Share failed: ",l),k(b,"share-failed")}}}function Tb(){return window.cordova&&window.cordova.plugins&&window.cordova.plugins.RateApp}function Rb(b){return new Promise((a,c)=>{window.requestFileSystem(window.TEMPORARY,b,d=>a(d.root),c)})}
function Sb(b,a){return new Promise((c,d)=>{a.getFile(b.name,{create:!0,exclusive:!1},e=>{const f=e.toURL();e.createWriter(g=>{g.onwriteend=()=>c(f);g.onerror=d;g.write(b)})},d)})}
self.da.xa(class extends self.pa{constructor(b){super(b,"share");b=!!Pb();this.ff="function"===typeof navigator.share||b;this.df=Ob()||b;t(this,[["init",()=>({isSupported:this.ff,isFilesSupported:this.df})],["share",a=>Qb(this,a)],["request-rate",a=>{const c=a.body,d=a.confirm,e=a.cancel;a=a.appID;const f=Tb();f&&f.Rate(c,d,e,a)}],["request-store",a=>{a=a.appID;const c=Tb();c&&c.Store(a)}]])}});"use strict";
async function Ub(b){if(!b.Ka)try{b.Ka=await navigator.wakeLock.request("screen"),b.Ka.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Ka=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
function Vb(){var b=document.body;const a=b.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");b=getComputedStyle(b);b=[b.getPropertyValue("--temp-sai-top"),b.getPropertyValue("--temp-sai-right"),b.getPropertyValue("--temp-sai-bottom"),b.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);
return isFinite(c)?c:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return b}
self.da.xa(class extends self.pa{constructor(b){super(b,"platform-info");t(this,[["get-initial-state",()=>this.Hc()],["request-wake-lock",()=>Ub(this)],["release-wake-lock",()=>{this.Ka&&(this.Ka.release(),this.Ka=null)}]]);window.addEventListener("resize",()=>{k(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:Vb()})});this.Ka=null}Hc(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:Vb(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";
self.da.xa(class extends self.pa{constructor(b){super(b,"avix-pokisdk-forc3");this.Sc=this.Ub=this.ea=!1;t(this,[["InitPoki",this.ve.bind(this)],["NotifyGameplayStart",this.Ce.bind(this)],["NotifyGameplayStop",this.wc.bind(this)],["HappyTime",this.ue.bind(this)],["RequestCommercialBreak",this.Ee.bind(this)],["RequestRewardedBreak",this.Fe.bind(this)],["SetDebugMode",this.sd.bind(this)],["GameLoadingFinished",this.te.bind(this)]])}te(){this.ea&&!this.Sc&&(this.Sc=!0,globalThis.PokiSDK.gameLoadingFinished())}Ce(){this.ea&&
(this.Sc||console.log("Don't forget to send the Loading Finished Notification, or configure the Poki Plugin to manage it automatically."),this.Ub=!0,globalThis.PokiSDK.gameplayStart())}wc(){this.ea&&(this.Ub=!1,globalThis.PokiSDK.gameplayStop())}ue({Gf:b}){this.ea&&globalThis.PokiSDK.happyTime(b)}Ee(){if(!this.ea)return{result:!1,Hb:!1};this.Ub&&this.wc();k(this,"SuspendRuntime");return globalThis.PokiSDK.commercialBreak().then(()=>{k(this,"ResumeRuntime");return{result:!0,Hb:!1}}).catch(b=>{console.error(b);
return{result:!1,Hb:b}})}Fe(){if(!this.ea)return{result:!1,Hb:!1};this.Ub&&this.wc();k(this,"SuspendRuntime");return globalThis.PokiSDK.rewardedBreak().then(b=>{k(this,"ResumeRuntime");return{result:b,Hb:!1}}).catch(b=>{console.error(b);return{result:!1,Hb:b}})}sd({enable:b}){this.ea&&globalThis.PokiSDK.setDebug(b)}ve({Ef:b,preventScroll:a}){if("undefined"!==typeof globalThis.PokiSDK){a&&this.preventScroll();this.ea=!0;let c=!1;return globalThis.PokiSDK.init().then(()=>{console.log("Poki SDK successfully initialized");
return{loaded:this.ea,ae:c}}).catch(()=>{console.log("Initialized, but the user likely has adblock");c=!0;return{loaded:this.ea,ae:c}}).finally(()=>{b&&this.sd(!0);globalThis.PokiSDK.gameLoadingStart()})}console.log("Poki SDK failed to load");return Promise.resolve({loaded:this.ea,ae:!1})}preventScroll(){window.addEventListener("keydown",b=>{["ArrowDown","ArrowUp"," "].includes(b.key)&&b.preventDefault()});window.addEventListener("wheel",b=>b.preventDefault(),{passive:!1})}});
